apiVersion: v1
kind: Service
metadata:
  name: python-example-service
spec:
  selector:
    app: python-example
  ports:
  - protocol: "TCP"
    port: 8088
    targetPort: 8080
  type: LoadBalancer

---

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-example
    spec:
      containers:
      - name: python-example
        image: python-example:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
