apiVersion: v1
kind: Service
metadata:
  name: ${CONTAINER_NAME}-service
spec:
  selector:
    app: ${CONTAINER_NAME}
  ports:
  - protocol: "TCP"
    port: 8910
    targetPort: 8910
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CONTAINER_NAME}-deployment
  labels:
    app: ${CONTAINER_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CONTAINER_NAME}
  template:
    metadata:
      labels:
        app: ${CONTAINER_NAME}
    spec:
      containers:
      - name: ${CONTAINER_NAME}
        image: ${DOCKER_DEPLOYMENT_IMAGE}
        imagePullPolicy: Never
        ports:
        - containerPort: 8910
